import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/lib/providers";
import { MotionProvider } from "@/lib/motion";
import { SmoothScroll } from "@/components/SmoothScroll";
import { ScrollProgress } from "@/components/ScrollProgress";
import { SiteHeader } from "@/components/home/SiteHeader";
import { Footer } from "@/components/layout/Footer";
import { ChromeFrame } from "@/components/layout/ChromeFrame";
import { TranslationProvider } from "@/hooks/useTranslation";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { ViewTransitionsProvider } from "@/components/ViewTransitionsProvider";
import { SkipToContent } from "@/components/wall/SkipToContent";
import {
  AriaLiveProvider,
  AriaLiveRegion,
} from "@/components/wall/AriaLiveRegion";
import "./globals.css";
// polish-2 T45 — above-the-fold critical CSS, inlined at the top of
// <body> to kill FOUC. Generated by `frontend/scripts/extract-critical-css.mjs`
// and read at server-render time (Next.js layouts are server components by
// default, so `fs.readFileSync` runs once per build / hot-reload).
import { readFileSync } from "node:fs";
import { join } from "node:path";
const criticalCss: string = (() => {
  try {
    return readFileSync(
      join(process.cwd(), "src/app/styles/critical.css"),
      "utf-8",
    );
  } catch {
    // Build hasn't run yet (or running in vitest with mocked cwd) —
    // ship an empty string; the global stylesheet still ships the rules.
    return "";
  }
})();

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const SITE_NAME = "GoWork";
const SITE_TAGLINE = "Workforce infrastructure for any American city.";
const SITE_DESCRIPTION = SITE_TAGLINE;

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://gowork.example";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_NAME,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/favicon-16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-icon.png", sizes: "180x180", type: "image/png" }],
    shortcut: ["/favicon.ico"],
  },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    images: [
      {
        url: "/og-image.svg",
        width: 1200,
        height: 630,
        alt: `${SITE_NAME} — ${SITE_TAGLINE}`,
      },
    ],
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    images: ["/og-image.svg"],
  },
};

export const viewport: Viewport = {
  themeColor: "#0A0E1A",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* SSR-safe theme boot. Reads localStorage["gowork-theme"] and
         * writes data-theme on <html> BEFORE React hydrates so the first
         * paint matches the user's saved preference and there's no flash
         * from dark→light (or vice versa) when SiteHeader hydrates and
         * runs its own theme mirror effect. Falls back to the system's
         * prefers-color-scheme on first visit. */}
        <script
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  // polish-3 round-3 — DARK is the canonical brand mode.
                  // Light is opt-in via the SiteHeader toggle ONLY (writes
                  // localStorage). We don't follow prefers-color-scheme any
                  // more because the editorial color story (warm-paper text
                  // on dark navy + cyan / amber path) only resolves in dark.
                  // A user whose OS is on light mode would otherwise land
                  // on a cream version of the page that looks broken.
                  var stored = window.localStorage.getItem('gowork-theme');
                  var theme = stored === 'light' ? 'light' : 'dark';
                  var html = document.documentElement;
                  html.setAttribute('data-theme', theme);
                  if (theme === 'dark') html.classList.add('dark');
                  else html.classList.remove('dark');
                } catch (e) { /* localStorage blocked — leave default */ }
              })();
            `,
          }}
        />
      </head>
      <body className={`${inter.variable} font-sans antialiased`}>
        {/* polish-2 T45 — inline above-the-fold critical CSS. Sits at
            the top of <body> so the first paint already has Ch1 hero +
            chrome rules without waiting on the global stylesheet
            roundtrip. */}
        <style
          data-critical-css
          dangerouslySetInnerHTML={{ __html: criticalCss as string }}
        />
        <Providers>
          <MotionProvider>
            <SmoothScroll>
              <AriaLiveProvider>
                <ScrollProgress />
                <ViewTransitionsProvider>
                  <TranslationProvider>
                    <SkipToContent />
                    {/* Universal site header — was previously the
                     *  legacy `<Header />` from `components/layout/Header`,
                     *  which still showed the legacy /
                     *  workforce-companion nav on every subpage even
                     *  though the home page rendered the new
                     *  facelift `<SiteHeader />`. ChromeFrame still
                     *  suppresses the layout chrome on `/` so the
                     *  HomePage's own internal `<SiteHeader />` stays
                     *  the only header on the home route — every other
                     *  route now also gets the same SiteHeader, so
                     *  the chrome is consistent across the entire
                     *  app. */}
                    <ChromeFrame>
                      <SiteHeader />
                    </ChromeFrame>
                    <ErrorBoundary>
                      <main
                        id="main"
                        className="flex min-h-[calc(100vh-3.5rem)] flex-col"
                      >
                        <div className="flex-1">{children}</div>
                        <ChromeFrame>
                          <Footer />
                        </ChromeFrame>
                      </main>
                    </ErrorBoundary>
                    <AriaLiveRegion />
                  </TranslationProvider>
                </ViewTransitionsProvider>
              </AriaLiveProvider>
            </SmoothScroll>
          </MotionProvider>
        </Providers>
      </body>
    </html>
  );
}
