"""Compose a downloadable Markdown document from a plan + profile.

The output is consumed by :func:`app.core.pdf_renderer.render_markdown_to_pdf`
to produce ``application/pdf`` bytes for the
``GET /api/plan/{session_id}/pdf`` endpoint.

Pure helper — no I/O, no Pydantic dependency on plan models so tests can
feed plain dicts straight off the ``/api/assessment/`` JSON envelope.
"""

from __future__ import annotations

from datetime import date
from typing import Any

__all__ = ["compose_plan_markdown"]


def compose_plan_markdown(plan: dict, profile: dict) -> str:
    """Return the canonical plan Markdown for PDF rendering."""
    parts: list[str] = []
    parts.append("# Your Personalized Plan")
    parts.append("")
    parts.append(_metadata_line(profile))
    parts.append("")

    summary = (plan.get("resident_summary") or "").strip()
    if summary:
        parts.extend(["## Your Story", "", summary, ""])

    parts.extend(_top_jobs_section(plan.get("job_matches") or []))
    parts.extend(_action_plan_section(plan.get("action_plan") or {}))
    parts.extend(_next_steps_section(plan.get("immediate_next_steps") or []))
    parts.extend(_footer_section(plan.get("action_plan") or {}))

    return "\n".join(parts).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Section helpers
# ---------------------------------------------------------------------------


def _metadata_line(profile: dict) -> str:
    zip_code = profile.get("zip_code") or "—"
    barriers = profile.get("primary_barriers") or []
    barriers_pretty = ", ".join(b.replace("_", " ").title() for b in barriers) or "None"
    return f"_ZIP {zip_code} · Focus areas: {barriers_pretty}_"


def _top_jobs_section(jobs: list[dict]) -> list[str]:
    if not jobs:
        return []
    out = ["## Top Job Matches", ""]
    for i, j in enumerate(jobs[:3], 1):
        title = j.get("title") or "Position"
        company = j.get("company") or "Employer"
        location = j.get("location") or "—"
        pay = j.get("pay_range") or "—"
        score = j.get("relevance_score")
        score_str = f"{score:.2f}" if isinstance(score, (int, float)) else "—"

        flags: list[str] = []
        if j.get("fair_chance"):
            flags.append("**Fair Chance**")
        if j.get("transit_accessible"):
            flags.append("**Transit-accessible**")
        flag_line = " · ".join(flags)

        out.append(f"### {i}. {title} — {company}")
        out.append(f"- **Location:** {location}")
        out.append(f"- **Pay:** {pay}")
        out.append(f"- **Match score:** {score_str}")
        if flag_line:
            out.append(f"- {flag_line}")
        out.append("")
    return out


def _action_plan_section(action_plan: dict) -> list[str]:
    phases = action_plan.get("phases") or []
    populated = [p for p in phases if (p.get("actions") or [])]
    if not populated:
        return []
    out = ["## Your Action Plan", ""]
    for ph in populated:
        out.append(f"### {ph.get('label') or ph.get('phase_id', '')}")
        out.append("")
        for a in ph.get("actions") or []:
            line = f"- **{a.get('title') or '(action)'}**"
            detail = (a.get("detail") or "").strip()
            if detail:
                line += f" — {detail}"
            out.append(line)
            res_name = a.get("resource_name")
            res_phone = a.get("resource_phone")
            res_addr = a.get("resource_address")
            contact_bits = []
            if res_phone:
                contact_bits.append(f"📞 {res_phone}")
            if res_addr:
                contact_bits.append(res_addr)
            if contact_bits and res_name and res_name != a.get("title"):
                out.append(f"  - {res_name} · " + " · ".join(contact_bits))
            elif contact_bits:
                out.append("  - " + " · ".join(contact_bits))
        out.append("")
    return out


def _next_steps_section(steps: list[Any]) -> list[str]:
    cleaned = [str(s).strip() for s in steps if str(s).strip()]
    if not cleaned:
        return []
    out = ["## Immediate Next Steps", ""]
    for s in cleaned:
        out.append(f"- {s}")
    out.append("")
    return out


def _footer_section(action_plan: dict) -> list[str]:
    today = action_plan.get("assessment_date") or date.today().isoformat()
    return [
        "---",
        "",
        f"_Generated by GoWork on {today}._",
        "_Resources verified for Fort Worth, TX._",
        "",
    ]
