"""Stall detector — classify session progress health (T12.18, S12a).

Reads progress signals from T12.23's EvidenceBundle (appointments, job
applications, outcomes) and classifies each session's
`days_since_last_progress` into a StallLevel (NONE / SOFT / MEDIUM /
HARD). Per-barrier attribution is driven by `appointment.barrier_link`;
session-wide signals (applications, generic outcomes) count toward
every barrier the session is working on only when that barrier has no
signal of its own — other barriers' signals never bleed over.

Auto-advance filtering
----------------------
Outcomes with `event_type='appointment_auto_advance'` are machine-
generated by the nightly appointment advancer, not worker actions. The
acceptance criteria call for filtering these "within a 48h window" — we
take the stricter, cleaner read: **filter auto_advance signals at ALL
ages**. An auto-generated record can never indicate forward motion by
the worker, so dropping it regardless of age is the semantically
correct rule. Real signals (attended appointments, filed applications,
worker-recorded outcomes) remain the ground truth for "last progress".

Active-session definition
-------------------------
A session is "active" when its `sessions` row has not yet expired
(`expires_at > now`). This matches the existing m001 schema (no
`status` column); we lean on the expiry timestamp rather than deriving
activity from scratch so the scan stays cheap on clean DBs.

S12a scope: detect + classify only. Reminder dispatch is T12.19 (S12b).
"""

from __future__ import annotations

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel

from app.modules.common.temporal_types import StallLevel
from app.modules.engagement.classification import (
    AUTO_ADVANCE_SUPPRESS_HOURS,
    HARD_DAYS,
    MEDIUM_DAYS,
    SOFT_DAYS,
    BarrierStall,
    build_barrier_stalls,
    classify_days,
    days_between,
    latest_per_barrier,
    level_rank,
)
from app.modules.engagement.progress_signals import collect_progress_events


class StalledSession(BaseModel):
    """Session-level stall summary with per-barrier breakdown."""

    session_id: str
    stalled_barriers: list[BarrierStall] = []
    days_stalled: int = 0
    stall_level: StallLevel = StallLevel.NONE


def _load_session_barriers(
    session_id: str, db_path: str | Path,
) -> list[str]:
    """Return the barrier_id list attached to `sessions.barriers`.

    Empty list falls back to session-level stall classification only.
    """
    conn = sqlite3.connect(str(db_path))
    try:
        row = conn.execute(
            "SELECT barriers FROM sessions WHERE id = ?", (session_id,),
        ).fetchone()
    finally:
        conn.close()
    if not row or not row[0]:
        return []
    try:
        parsed = json.loads(row[0])
    except (json.JSONDecodeError, TypeError):
        return []
    if not isinstance(parsed, list):
        return []
    return [b for b in parsed if isinstance(b, str)]


def _session_level_fallback(
    session_id: str,
    events_by_barrier: dict[str | None, list[datetime]],
    now: datetime,
) -> StalledSession:
    """Classify session-level stall when no enumerable barriers exist."""
    global_events = events_by_barrier.get(None, [])
    latest = max(global_events) if global_events else None
    days = days_between(now, latest) if latest else 0
    level = classify_days(days) if latest else StallLevel.NONE
    return StalledSession(
        session_id=session_id,
        stalled_barriers=[],
        days_stalled=days,
        stall_level=level,
    )


def compute_stall_for_session(
    session_id: str,
    *,
    db_path: str | Path,
    now: datetime | None = None,
) -> StalledSession:
    """Compute stall level(s) for one session.

    Idempotent: two calls with the same `now` and unchanged DB produce
    identical results (no state is written).
    """
    now = now or datetime.now(timezone.utc)
    events_by_barrier = collect_progress_events(
        session_id, db_path=db_path, now=now,
    )
    barriers = _load_session_barriers(session_id, db_path)
    if not barriers:
        return _session_level_fallback(session_id, events_by_barrier, now)

    latest_by_barrier = latest_per_barrier(events_by_barrier, barriers)
    stalled_barriers = build_barrier_stalls(latest_by_barrier, now)
    days = max((b.days_stalled for b in stalled_barriers), default=0)
    worst_level = max(
        (b.stall_level for b in stalled_barriers),
        key=level_rank,
        default=StallLevel.NONE,
    )
    return StalledSession(
        session_id=session_id,
        stalled_barriers=stalled_barriers,
        days_stalled=days,
        stall_level=worst_level,
    )


def _active_session_ids(db_path: str | Path, now: datetime) -> list[str]:
    """Return session IDs whose `expires_at` is still in the future."""
    conn = sqlite3.connect(str(db_path))
    try:
        rows = conn.execute(
            "SELECT id, expires_at FROM sessions",
        ).fetchall()
    finally:
        conn.close()
    active: list[str] = []
    now_iso = now.isoformat()
    for sid, expires_at in rows:
        if not expires_at or expires_at >= now_iso:
            active.append(sid)
    return active


def scan_active_sessions(
    *,
    db_path: str | Path,
    now: datetime | None = None,
) -> list[StalledSession]:
    """Iterate active sessions; return only those with a stall level > NONE."""
    now = now or datetime.now(timezone.utc)
    out: list[StalledSession] = []
    for sid in _active_session_ids(db_path, now):
        stalled = compute_stall_for_session(sid, db_path=db_path, now=now)
        if stalled.stall_level is not StallLevel.NONE:
            out.append(stalled)
    return out


__all__ = [
    "AUTO_ADVANCE_SUPPRESS_HOURS",
    "BarrierStall",
    "HARD_DAYS",
    "MEDIUM_DAYS",
    "SOFT_DAYS",
    "StalledSession",
    "compute_stall_for_session",
    "scan_active_sessions",
]
