/**
 * Carlos's path layer (T2.14, W3-Ch7 ready).
 *
 * **W2 scope:** renders only the home pin (representative block) at the
 * coordinates exported by `paths.ts`. The W3 Ch7 LineString that traces
 * Carlos's 5-waypoint path is pre-registered with `visibility: none` so
 * W3 only flips a single layer property (Compound Lens — feed-W3-without-
 * refactor).
 *
 * Source GeoJSON is generated in code from `paths.ts` (single source of
 * truth). The committed file under `/data/wall/carlos-path.geojson` is
 * regenerated by the same builder so reviewers see one stable artifact.
 */

import { CARLOS_HOME_PIN, CARLOS_PATH_WAYPOINTS } from "../paths";
import { TARRANT_OFFICES } from "../officeRegistry";
import { registerLayer, removeLayer } from "./lifecycle";
import type {
  GeoJSONSourceConfig,
  MapboxLayerSpec,
  MapboxLikeMap,
  WallDataLayer,
} from "./types";

export const CARLOS_PATH_SOURCE_ID = "carlos-path-source";
export const CARLOS_HOME_SYMBOL_ID = "carlos-home-symbol";
export const CARLOS_PATH_LINE_ID = "carlos-path-line";

const AMBER_STRONG = "oklch(0.86 0.18 80)";
const CYAN = "oklch(0.78 0.13 215)";

interface PathFeatureCommon {
  type: "Feature";
  properties: {
    kind: "home" | "waypoint" | "trace";
    label: string;
    week?: number;
    office?: string;
    piiSafe?: boolean;
  };
}

type PathPointFeature = PathFeatureCommon & {
  geometry: { type: "Point"; coordinates: [number, number] };
};

type PathLineFeature = PathFeatureCommon & {
  geometry: { type: "LineString"; coordinates: [number, number][] };
};

export type CarlosPathFeature = PathPointFeature | PathLineFeature;

export interface CarlosPathFeatureCollection {
  type: "FeatureCollection";
  features: CarlosPathFeature[];
}

function resolveWaypointCoord(officeId: string): [number, number] | null {
  if (officeId === "home") {
    return [CARLOS_HOME_PIN.longitude, CARLOS_HOME_PIN.latitude];
  }
  const office = TARRANT_OFFICES.find((o) => o.id === officeId);
  return office ? [office.longitude, office.latitude] : null;
}

/**
 * Build the source GeoJSON: home Point + waypoint Points + trace
 * LineString. Pure function; same output drives both runtime + committed.
 */
export function buildCarlosPathGeoJSON(): CarlosPathFeatureCollection {
  const features: CarlosPathFeature[] = [];

  features.push({
    type: "Feature",
    properties: {
      kind: "home",
      label: CARLOS_HOME_PIN.label,
      piiSafe: CARLOS_HOME_PIN.piiSafe,
    },
    geometry: {
      type: "Point",
      coordinates: [CARLOS_HOME_PIN.longitude, CARLOS_HOME_PIN.latitude],
    },
  });

  const traceCoords: [number, number][] = [];
  for (const wp of CARLOS_PATH_WAYPOINTS) {
    const coord = resolveWaypointCoord(wp.office);
    if (!coord) continue;
    traceCoords.push(coord);
    if (wp.office !== "home") {
      features.push({
        type: "Feature",
        properties: {
          kind: "waypoint",
          label: wp.label,
          week: wp.week,
          office: wp.office,
        },
        geometry: { type: "Point", coordinates: coord },
      });
    }
  }

  features.push({
    type: "Feature",
    properties: { kind: "trace", label: "Carlos 5-week plan" },
    geometry: { type: "LineString", coordinates: traceCoords },
  });

  return { type: "FeatureCollection", features };
}

const sourceConfig: GeoJSONSourceConfig = {
  type: "geojson",
  data: "/data/wall/carlos-path.geojson",
  generateId: false,
  // W3 Ch7 — line-gradient on the trace requires per-vertex line-progress
  // metrics. Mapbox computes them at source level; W2's hidden trace also
  // benefits because the property is a no-op when visibility is none.
  lineMetrics: true,
};

/** Home pin: amber dot, fades in during Ch3. */
const homeSymbolLayer: MapboxLayerSpec = {
  id: CARLOS_HOME_SYMBOL_ID,
  type: "circle",
  source: CARLOS_PATH_SOURCE_ID,
  filter: ["==", ["get", "kind"], "home"],
  paint: {
    "circle-radius": 8,
    "circle-color": AMBER_STRONG,
    "circle-stroke-color": CYAN,
    "circle-stroke-width": 2,
    "circle-opacity": 0.95,
  },
  minzoom: 11,
};

/** Trace line — hidden in W2; W3 Ch7 flips visibility on. */
const pathLineLayer: MapboxLayerSpec = {
  id: CARLOS_PATH_LINE_ID,
  type: "line",
  source: CARLOS_PATH_SOURCE_ID,
  filter: ["==", ["get", "kind"], "trace"],
  layout: {
    visibility: "none",
    "line-cap": "round",
    "line-join": "round",
  },
  paint: {
    "line-color": AMBER_STRONG,
    "line-width": 2,
    "line-opacity": 0.85,
    "line-dasharray": [1, 2],
  },
  minzoom: 11,
};

const layerConfigs: readonly MapboxLayerSpec[] = [
  pathLineLayer,
  homeSymbolLayer,
] as const;
const layerIds: readonly string[] = [CARLOS_PATH_LINE_ID, CARLOS_HOME_SYMBOL_ID] as const;

export const carlosPathLayer: WallDataLayer = {
  sourceId: CARLOS_PATH_SOURCE_ID,
  layerIds,
  sourceConfig,
  layerConfigs,
  register(map: MapboxLikeMap) {
    registerLayer(map, CARLOS_PATH_SOURCE_ID, sourceConfig, layerConfigs);
  },
  remove(map: MapboxLikeMap) {
    removeLayer(map, CARLOS_PATH_SOURCE_ID, layerIds);
  },
};
