/**
 * Tarrant County offices layer (T2.12) + W3 future-proof state machine
 * (T2.128).
 *
 * Source GeoJSON is **derived in code** from the verified registry
 * (`officeRegistry.ts`) — single source of truth. The committed file at
 * `/data/wall/tarrant-offices.geojson` is regenerated by the same
 * function so editorial reviewers see one stable artifact.
 *
 * Paint expression supports 4 office states:
 *   - `default`    : low opacity, sprite per category
 *   - `highlighted`: full opacity (W2 Ch4 sub-chapters)
 *   - `visited`    : dimmed amber (W3 Ch7 — Carlos has been here)
 *   - `current`    : bright cyan (W3 Ch7 — Carlos is here now)
 *
 * W2 renders `default` + `highlighted` only. W3 enables the other two
 * states without re-shipping the layer module — the contract is fixed
 * here in W2 (Compound Lens efficiency).
 */

import { TARRANT_OFFICES, type VerifiedOffice } from "../officeRegistry";
import { registerLayer, removeLayer } from "./lifecycle";
import type {
  GeoJSONSourceConfig,
  MapboxLayerSpec,
  MapboxLikeMap,
  WallDataLayer,
} from "./types";

export const OFFICES_SOURCE_ID = "tarrant-offices-source";
export const OFFICES_SYMBOL_ID = "tarrant-offices-symbol";

export interface OfficeFeature {
  type: "Feature";
  properties: VerifiedOffice;
  geometry: { type: "Point"; coordinates: [number, number] };
}

export interface OfficeFeatureCollection {
  type: "FeatureCollection";
  features: OfficeFeature[];
}

/**
 * Convert the registry into a GeoJSON FeatureCollection.
 *
 * Pure function — feeds both the runtime Mapbox source and the
 * pre-committed `tarrant-offices.geojson` (regen step).
 */
export function buildOfficesGeoJSON(): OfficeFeatureCollection {
  return {
    type: "FeatureCollection",
    features: TARRANT_OFFICES.map((office) => ({
      type: "Feature" as const,
      properties: office,
      geometry: {
        type: "Point" as const,
        coordinates: [office.longitude, office.latitude],
      },
    })),
  };
}

const sourceConfig: GeoJSONSourceConfig = {
  type: "geojson",
  data: "/data/wall/tarrant-offices.geojson",
  generateId: false, // We use our own stable office.id as the feature id.
};

/**
 * Symbol layer with category-aware iconImage + state-aware opacity.
 *
 * `icon-image` lookup pulls from the sprite (`markerSymbols.ts` + the
 * runtime sprite registration in MapboxScene); the category prefix
 * (`gowork-`) namespaces our sprite from any default Mapbox sprites.
 */
const symbolLayer: MapboxLayerSpec = {
  id: OFFICES_SYMBOL_ID,
  type: "symbol",
  source: OFFICES_SOURCE_ID,
  layout: {
    "icon-image": [
      "concat",
      "gowork-office-",
      ["get", "category"],
    ],
    "icon-size": [
      "match",
      ["get", "state"],
      "current",
      1.0,
      "highlighted",
      0.9,
      0.7,
    ],
    "icon-allow-overlap": true,
    "icon-ignore-placement": true,
  },
  paint: {
    "icon-opacity": [
      "match",
      ["get", "state"],
      "default",
      0.55,
      "highlighted",
      1.0,
      "visited",
      0.4,
      "current",
      1.0,
      0.55,
    ],
  },
  minzoom: 9,
};

const layerConfigs: readonly MapboxLayerSpec[] = [symbolLayer] as const;
const layerIds: readonly string[] = [OFFICES_SYMBOL_ID] as const;

export const officesLayer: WallDataLayer = {
  sourceId: OFFICES_SOURCE_ID,
  layerIds,
  sourceConfig,
  layerConfigs,
  register(map: MapboxLikeMap) {
    registerLayer(map, OFFICES_SOURCE_ID, sourceConfig, layerConfigs);
  },
  remove(map: MapboxLikeMap) {
    removeLayer(map, OFFICES_SOURCE_ID, layerIds);
  },
};
