"""Markdown-to-PDF renderer (T12.4) with SSRF-guarded WeasyPrint.

Public entry point: :func:`render_markdown_to_pdf`.

Security model
--------------
Worker-supplied content (names, employer, notes) reaches this renderer.
Two defences are layered:

1.  **WeasyPrint ``url_fetcher``** is replaced with a deny-all stub
    (:func:`_deny_all_url_fetcher`) that raises ``URLFetchingError``
    for every URL. This prevents SSRF via worker-controlled
    ``<img src>``, ``<link href>``, or CSS ``@import``.
2.  **Jinja2 ``Environment(autoescape=True)``** so any direct
    ``{{ var }}`` interpolation escapes HTML metacharacters. Only
    ``{{ body | safe }}`` is trusted — the body is pre-generated by
    the ``markdown`` library which escapes raw HTML in worker input
    (we do not enable ``md_in_html`` or unsafe extensions).

Templates live under
``backend/app/modules/documents/templates/<template_name>.html``
and are created in sibling tasks (T12.14).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import markdown as _markdown
from jinja2 import Environment, FileSystemLoader, TemplateNotFound, select_autoescape

__all__ = ["PdfRenderError", "render_markdown_to_pdf"]


class PdfRenderError(RuntimeError):
    """Raised when PDF rendering fails for a non-transient reason."""


_DEFAULT_TEMPLATES_DIR = (
    Path(__file__).resolve().parents[1] / "modules" / "documents" / "templates"
)
_MARKDOWN_EXTENSIONS = ["extra"]
_DEFAULT_TITLE = "Document"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_markdown_to_pdf(
    markdown_content: str,
    template_name: str = "default",
    *,
    templates_dir: Path | None = None,
) -> bytes:
    """Render ``markdown_content`` through a Jinja2 HTML template to PDF bytes.

    Parameters
    ----------
    markdown_content:
        CommonMark-ish markdown. Raw ``<html>`` in the input is escaped
        by the markdown library (``md_in_html`` is **not** enabled).
    template_name:
        Base name of the template under ``templates_dir`` (without
        ``.html`` suffix). Defaults to ``"default"``.
    templates_dir:
        Directory that holds the Jinja2 templates. Defaults to
        ``backend/app/modules/documents/templates``.

    Returns
    -------
    bytes
        The rendered PDF, starting with the ``%PDF-`` magic bytes.

    Raises
    ------
    PdfRenderError
        When the template cannot be located or PDF rendering fails.
    """
    resolved_dir = _resolve_templates_dir(templates_dir)
    env = _build_jinja_env(resolved_dir)
    html_document = _render_html(env, template_name, markdown_content)
    return _html_to_pdf(html_document)


# ---------------------------------------------------------------------------
# Internal helpers (exposed for tests)
# ---------------------------------------------------------------------------


def _deny_all_url_fetcher(url: str) -> dict[str, Any]:
    """SSRF defence: refuse every external URL.

    WeasyPrint's ``url_fetcher`` hook is invoked for any reference the
    HTML/CSS pipeline wants to resolve. Raising ``URLFetchingError``
    here guarantees no network call is made regardless of what the
    worker-supplied content tries to reference.
    """
    from weasyprint.urls import URLFetchingError

    raise URLFetchingError(f"External URL fetch denied: {url!r}")


def _build_jinja_env(templates_dir: Path) -> Environment:
    """Construct a Jinja2 ``Environment`` with autoescape on for HTML."""
    return Environment(
        loader=FileSystemLoader(str(templates_dir)),
        autoescape=select_autoescape(
            enabled_extensions=("html", "htm", "xml"),
            default_for_string=True,
        ),
    )


def _extract_title(markdown_content: str) -> str:
    """Return the first ATX H1 heading or the default title."""
    for line in markdown_content.splitlines():
        stripped = line.strip()
        match = re.match(r"^#\s+(.+?)\s*#*\s*$", stripped)
        if match:
            return match.group(1).strip()
    return _DEFAULT_TITLE


# ---------------------------------------------------------------------------
# Private composition helpers
# ---------------------------------------------------------------------------


def _resolve_templates_dir(templates_dir: Path | None) -> Path:
    """Return an existing templates directory or raise ``PdfRenderError``."""
    resolved = templates_dir or _DEFAULT_TEMPLATES_DIR
    if not resolved.is_dir():
        raise PdfRenderError(
            f"Templates directory does not exist: {resolved}"
        )
    return resolved


def _render_html(
    env: Environment, template_name: str, markdown_content: str
) -> str:
    """Render the Jinja2 template with markdown converted to HTML."""
    try:
        template = env.get_template(f"{template_name}.html")
    except TemplateNotFound as exc:
        raise PdfRenderError(
            f"Template not found: {template_name!r}"
        ) from exc

    body_html = _markdown.markdown(
        markdown_content,
        extensions=_MARKDOWN_EXTENSIONS,
        output_format="html",
    )
    title = _extract_title(markdown_content)
    return template.render(title=title, body=body_html)


def _html_to_pdf(html_document: str) -> bytes:
    """Render an HTML string to PDF with the deny-all URL fetcher."""
    # Imported lazily so module import does not fail when the native
    # WeasyPrint dependencies are unavailable (e.g. static analysis).
    from weasyprint import HTML

    try:
        pdf_bytes = HTML(
            string=html_document,
            url_fetcher=_deny_all_url_fetcher,
        ).write_pdf()
    except Exception as exc:  # noqa: BLE001 - WeasyPrint raises diverse types
        raise PdfRenderError(f"PDF rendering failed: {exc}") from exc
    if not pdf_bytes:
        raise PdfRenderError("WeasyPrint returned empty output")
    return pdf_bytes
